//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenBastard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IisConfigFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IisConfigFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenBastard.IisConfigFiles", typeof(IisConfigFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--
        ///
        ///    IIS configuration sections.
        ///
        ///    For schema documentation, see
        ///    %windir%\system32\inetsrv\config\schema\IIS_schema.xml.
        ///    
        ///    Please make a backup of this file before making any changes to it.
        ///
        ///--&gt;
        ///
        ///&lt;configuration&gt;
        ///
        ///  &lt;!--
        ///
        ///        The &lt;configSections&gt; section controls the registration of sections.
        ///        Section is the basic unit of deployment, locking, searching and
        ///        containment for configuration settings.
        ///        
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string iis7config {
            get {
                return ResourceManager.GetString("iis7config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;configSections&gt;
        ///  &lt;/configSections&gt;
        ///  &lt;appSettings /&gt;
        ///
        ///  &lt;system.web&gt;
        ///    &lt;!-- 
        ///            Set compilation debug=&quot;true&quot; to insert debugging 
        ///            symbols into the compiled page. Because this 
        ///            affects performance, set this value to true only 
        ///            during development.
        ///        --&gt;
        ///    &lt;compilation debug=&quot;true&quot; numRecompilesBeforeAppRestart=&quot;1&quot; &gt;
        ///      &lt;assemblies&gt;
        ///        &lt;add assembly=&quot;System.Core, Version=3.5. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string webconfig {
            get {
                return ResourceManager.GetString("webconfig", resourceCulture);
            }
        }
    }
}
