
Type.createNamespace('ScriptFX.Net');ScriptFX.Net._XDAjax$1=function(request,data){this.$1=new Date();this.$0=request;this.$2=data;}
ScriptFX.Net._XDAjax$1.prototype={$0:null,$1:null,$2:null,$3:null,get_contentLength:function(){return 0;},get_contentType:function(){return 'text/javascript';},get_headers:function(){return {};},get_request:function(){return this.$0;},get_statusCode:function(){return 200;},get_statusText:function(){return String.Empty;},get_timeStamp:function(){return this.$1;},getHeader:function($p0){return null;},getObject:function(){return this.$2;},getText:function(){return Type.safeCast(this.$2,String);},getXML:function(){if(!this.$3){var $0=this.getText();if($0){try{this.$3=XMLDocumentParser.parse($0);}catch($1){}}}return this.$3;}}
ScriptFX.Net.ScriptTransport=function(request){ScriptFX.Net.ScriptTransport.constructBase(this,[request]);}
ScriptFX.Net.ScriptTransport.prototype={$1_0:null,$1_1:null,abort:function(){if(this.$1_1){Delegate.clearExport(this.$1_1);this.$1_1=null;}if(this.$1_0){document.body.removeChild(this.$1_0);this.$1_0=null;}},dispose:function(){this.abort();},invoke:function(){var $0=null;var $1=this.get_parameters();if($1){$0=$1['callbackParameterName'];}if(!$0){$0='callback';}var $2=Delegate.create(this,this.$1_2);this.$1_1=Delegate.createExport($2);var $3=$0+'=Delegate.'+this.$1_1;var $4=this.get_request().get_URI();if($4.indexOf('?')>=0){$4+='&'+$3;}else{$4+='?'+$3;}this.$1_0=document.createElement('SCRIPT');this.$1_0.type='text/javascript';this.$1_0.src=$4;document.body.appendChild(this.$1_0);},$1_2:function($p0){if(this.$1_0){document.body.removeChild(this.$1_0);this.$1_0=null;this.$1_1=null;this.onCompleted(new ScriptFX.Net._XDAjax$1(this.get_request(),$p0));}}}
ScriptFX.Net._XDAjax$1.createClass('ScriptFX.Net._XDAjax$1',null,ScriptFX.Net.IHTTPResponse);ScriptFX.Net.ScriptTransport.createClass('ScriptFX.Net.ScriptTransport',ScriptFX.Net.HTTPTransport);
// ---- Do not remove this footer ----
// Generated using Script# v0.5.1.0 (http://projects.nikhilk.net)
// -----------------------------------
